# Generated by Django 3.0.1 on 2020-01-01 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('respose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Choice')),
            ],
        ),
    ]
