# Generated by Django 3.0.1 on 2020-01-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200101_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
