# Generated by Django 3.0.1 on 2020-01-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20200101_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='respose',
            new_name='response',
        ),
    ]
